name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # You can add more OSes if needed
        
    steps:
    - uses: actions/checkout@v3

    - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.6.1
        with:
          python_ver: '3.8'
          pyinstaller_ver: '==6.10.2'
          spec: 'listener.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'TSS-BROWSERLOCK LISTENER'
          options: --onefile, --name "TSS BROWSERLOCK LISTENER", --windowed, --noconsole, 
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: dist
