name: Build Executable (MAIN.PY)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # You can add more OSes if needed
        
    steps:
    - uses: actions/checkout@v3

    - name: Create Executable
        uses: Martin005/pyinstaller-action@1.2.0
        with:
          python_ver: '3.8'
          pyinstaller_ver: '==6.10.2'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'TSS-BROWSERLOCK'
          options: --onefile, --name "TSS BROWSERLOCK", --windowed, --noconsole, 
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: dist
